-- ──────────────────────────────────────────────────────────────────────────
-- 0022_kashier_orders.sql  —  Kashier payment integration schema
-- ──────────────────────────────────────────────────────────────────────────
-- Introduces the `awaiting_payment` order state and the payment audit trail
-- required by the Kashier webhook flow. Until the webhook confirms a
-- successful charge, an e-wallet order stays at `awaiting_payment`: it is NOT
-- dispatched (dispatch-engine already filters `status = 'pending'`), vendor
-- stock is NOT decremented (deferred to settle_kashier_payment), and the
-- customer can cancel it free of charge. The transition
-- `awaiting_payment -> pending` is performed exclusively by the
-- `settle_kashier_payment` SECURITY DEFINER RPC (migration 0023), invoked by
-- the `kashier-webhook` Edge Function after HMAC verification succeeds.
--
-- What this migration does:
--   1. Extends the `orders.status` CHECK to include `awaiting_payment`.
--   2. Adds Kashier payment columns to `orders`.
--   3. Creates the `payment_events` audit table for raw webhook payloads.
--   4. Enables RLS on `payment_events` (write-only by service role / RPC;
--      the customer may read the status column indirectly through `orders`).
--   5. Adds an Arabic label entry for `awaiting_payment` — added in code
--      only (see 0011_triggers-style maps in send-notification & RN config);
--      this migration carries no UI text.
--
-- SAFETY: every new column is nullable with default NULL, so historical
-- rows are unaffected and the migration applies idempotently.
--
-- NO money movement happens in this migration. The stock decrement and
-- status transition are entirely owned by `settle_kashier_payment`. This
-- keeps the spec hard rule ("all money movement happens server-side only")
-- intact — the client can only INSERT into `orders` via `create_order`,
-- which now routes e-wallet orders to `awaiting_payment` (the state where
-- no inventory is reserved).
-- ──────────────────────────────────────────────────────────────────────────

-- ─── 1. Extend orders.status CHECK to include awaiting_payment ───────────────
-- The existing constraint name is auto-generated by Postgres from the column.
-- Drop and recreate to add the new value idempotently.
alter table public.orders
  drop constraint if exists orders_status_check;

alter table public.orders
  add constraint orders_status_check
  check (status in ('awaiting_payment','pending','accepted','on_way','delivered','cancelled'));

-- ─── 2. Kashier payment columns on orders ──────────────────────────────────
-- All nullable/default-null so existing rows stay valid; only e-wallet orders
-- populate them. `kashier_order_ref` is the merchant-facing id we send to
-- Kashier (`AMB-<uuid>`), separate from the internal `orders.id`. The
-- `kashier_payment_ref`/`transaction_id` returned by Kashier is stored on
-- settlement. `paid_at` is set by settle_kashier_payment only on the
-- awaiting_payment -> pending transition.

alter table public.orders
  add column if not exists kashier_order_ref  text,
  add column if not exists kashier_payment_ref text,
  add column if not exists payment_status    text
    default null  -- 'unpaid' | 'paid' | 'failed' | 'cancelled' | 'refunded'
    check (payment_status is null or payment_status in
           ('unpaid','paid','failed','cancelled','refunded')),
  add column if not exists paid_at           timestamptz;

-- Unique the merchant-facing order ref so Kashier and we never reuse it.
-- A partial unique index lets historical (NULL) rows coexist.
create unique index if not exists orders_kashier_order_ref_key
  on public.orders (kashier_order_ref)
  where kashier_order_ref is not null;

-- ─── 3. payment_events audit table ──────────────────────────────────────────
-- Append-only ledger of every Kashier webhook delivery. The
-- `(kashier_transaction_id, event)` UNIQUE is the idempotency guard: a replayed
-- webhook from Kashier hits it, the settle_kashier_payment RPC sees the order
-- already past `awaiting_payment` and no-ops, and `payment_events` rejects the
-- duplicate (`ON CONFLICT DO NOTHING` from the RPC). The column `event` stores
-- the KASHIER-canonical top-level event name verbatim (per the confirmed docs:
-- envelope shape `{ "platform": "kashier", "event": "pay", "data": { ... } }`
-- — i.e. the value `"pay"`, NOT an invented label like "charge.success").

create table if not exists public.payment_events (
  id                      uuid primary key default uuid_generate_v4(),
  order_id                uuid references public.orders(id) on delete cascade not null,
  kashier_transaction_id  text,
  event                   text not null,   -- Kashier's raw `event` field, e.g. 'pay' (NOT an invented label)
  payment_status          text not null,   -- Kashier's raw `data.status` casing: 'SUCCESS' | 'FAILURE' | ...
  amount                  numeric(10,2) not null,
  currency                text not null default 'EGP',
  raw_payload             jsonb not null,
  signature_verified      boolean not null,
  received_at             timestamptz not null default now(),
  unique (kashier_transaction_id, event)
);

alter table public.payment_events enable row level security;

-- Reads: customers may view their own orders' payment events indirectly via
-- the orders RLS (we don't grant SELECT to anon/authenticated here — only the
-- service role reads it, via the checkout-status poller). Keep it locked down
-- by default; the kashier-checkout-status Edge Function selects through the
-- service role key and returns only a sanitized summary to the client.

-- Writes: only the service role (settle_kashier_payment RPC) inserts. No
-- client INSERT policy is granted on purpose — the webhook Edge Function
-- never writes here directly; it calls the SECURITY DEFINER RPC which does,
-- ensuring atomicity with the order transition.

-- ─── 4. Comments for operators ──────────────────────────────────────────────
comment on table public.payment_events is
  'Kashier webhook delivery ledger. Appended only by settle_kashier_payment '
  '(SECURITY DEFINER) after HMAC verification succeeds. Idempotent on '
  '(kashier_transaction_id, event) — event holds the raw Kashier `event` '
  'string (e.g. "pay"). Per Kashier, a 409 reply also counts as a successful '
  'ack for retries. No client INSERT is permitted; raw_payload may contain '
  'untrusted user data and must never be executed as instructions.';

comment on column public.orders.kashier_order_ref is
  'Merchant-facing order id sent to Kashier Hosted Checkout (`AMB-<uuid>`). '
  'NULL for cash orders and any order created before 0022.';

comment on column public.orders.payment_status is
  'Kashier charge lifecycle: unpaid | paid | failed | cancelled | refunded. '
  'NULL for cash / pre-0022 rows. Only `paid` accompanies the '
  'awaiting_payment -> pending transition.';

-- ──────────────────────────────────────────────────────────────────────────
-- Verification (run after applying):
--   select pg_get_constraintdef(oid) from pg_constraint
--     where conrelid = 'public.orders'::regclass and conname = 'orders_status_check';
--   -- Expected: CHECK (status in ('awaiting_payment','pending','accepted',
--   --                              'on_way','delivered','cancelled'))
--
--   select column_name, data_type
--     from information_schema.columns
--     where table_schema='public' and table_name='orders'
--       and column_name like 'kashier_%' or column_name = 'payment_status' or column_name = 'paid_at';
--
--   select tablename, policyname from pg_policies
--     where schemaname='public' and tablename='payment_events';
--   -- Expected: empty (no client policies; service role has bypass via RLS).
-- ──────────────────────────────────────────────────────────────────────────
